/*
-- IMPLICITOS
-- EXPLICITOS

-- IMPLICITOS
SQL%ISOPEN -- FALSE para implicitos
SQL%FOUND
SQL%NOTFOUND
SQL%ROWCOUNT

SELECT 1

SELECT 2

SQL%FOUND -- solo se atribuye al select 2
*/
BEGIN
    UPDATE TEST SET C2='PPPP' WHERE C1=20;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ENCONTRADO');
    END IF;
    
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO');
    END IF;
END;
   /
