CREATE OR REPLACE PACKAGE PACK1
IS
  FUNCTION CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR) return VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PACK1
IS
FUNCTION UP(NAME VARCHAR2)
RETURN VARCHAR2 
IS
BEGIN
    RETURN UPPER(NAME);
END UP;

FUNCTION DO(NAME VARCHAR2)
RETURN VARCHAR2 
IS
BEGIN
    RETURN LOWER(NAME);
END DO;

FUNCTION CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR) RETURN VARCHAR2
 IS
 BEGIN
    IF CONVERSION_TYPE='U' THEN
       RETURN(UP(NAME));
    ELSIF CONVERSION_TYPE='L' THEN
       RETURN(DO(NAME));
    ELSE
       RETURN('EL PARAMETRO DEBE SER U o L');
   END IF;
END CONVERT;

END PACK1;










---------------
SET SERVEROUTPUT ON
DECLARE
  V1 VARCHAR2(100);
BEGIN
 V1:=PACK1.CONVERT('AAAAA','L');
 DBMS_OUTPUT.PUT_LINE(V1);
END;
/

SELECT
    first_name,PACK1.CONVERT(FIRST_NAME,'L'),PACK1.CONVERT(LAST_NAME,'U')
FROM
    employees;


