--USER_OBJECTS
SELECT * FROM USER_OBJECTS 
WHERE OBJECT_TYPE='PROCEDURE';

SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS
GROUP BY OBJECT_TYPE;

SELECT * FROM USER_SOURCE
WHERE NAME='PR1';

SELECT TEXT FROM USER_SOURCE
WHERE NAME='PR1';