CREATE OR REPLACE TRIGGER trigger1 
FOR DELETE OR INSERT OR UPDATE ON regions
COMPOUND TRIGGER
    BEFORE STATEMENT IS BEGIN
        INSERT INTO LOG_TABLE VALUES('BEFORE STATEMENT',USER);
    END BEFORE STATEMENT;
    
    AFTER STATEMENT IS BEGIN
        INSERT INTO LOG_TABLE VALUES('AFTER STATEMENT',USER);
    END AFTER STATEMENT;
    
    BEFORE EACH ROW IS BEGIN
        INSERT INTO LOG_TABLE VALUES('BEFORE EACH ROW',USER);
    END BEFORE EACH ROW;
   
   AFTER EACH ROW IS BEGIN
        INSERT INTO LOG_TABLE VALUES('AFTER EACH ROW',USER);
    END AFTER EACH ROW;
END trigger1;