--PRACTICA 1 INICIALES
DECLARE
        NOMBRE VARCHAR2(20);
        APELLIDO1 VARCHAR2(20);
        APELLIDO2 VARCHAR2(20);
        INICIALES VARCHAR2(6);
BEGIN
    NOMBRE:='pedro';
    APELLIDO1:='garcia';
    APELLIDO2:='Rodrigiuez';
    INICIALES:=SUBSTR(NOMBRE,1,1)||'.'||SUBSTR(APELLIDO1,1,1)||'.'||SUBSTR(APELLIDO2,1,1)||'.';
    DBMS_OUTPUT.PUT_LINE(UPPER(INICIALES));
END;
/
    
-- PRACTICA2- DIA DE NACIMIENTO
DECLARE
    FEC_NAC DATE;
    DIA_SEMANA VARCHAR2(100);
BEGIN
    FEC_NAC:=TO_DATE('10/10/1965');
    DIA_SEMANA:=TO_CHAR(FEC_NAC,'DAY');
    DBMS_OUTPUT.PUT_LINE(DIA_SEMANA);
END;
/
    
    